language: cpp
compiler:
  - g++
before_install:
  - pip install --user cpp-coveralls
  - pip install --user scons
  - sudo wget -O boost_1_74_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.74.0/boost_1_74_0.tar.gz/download
  - sudo tar xzf boost_1_74_0.tar.gz
  - cd boost_1_74_0/
  - sudo mkdir /usr/local/lib/boost_cpp
  - sudo mkdir /usr/local/lib/boost_cpp/boost_work
  - sudo mkdir /usr/local/lib/boost_cpp/boost_work/build-dir
  - sudo ./bootstrap.sh --prefix=/usr/local/lib/boost_cpp/boost_work --with-toolset=gcc
  - sudo ./b2 --prefix=/usr/local/lib/boost_cpp/boost_work toolset=gcc --build-dir=/usr/local/lib/boost_cpp/boost_work/build-dir --with-test link=static -a
  - sudo cp -r ../boost_1_74_0/ /usr/local/lib/boost_cpp
  - cd ..
  - sudo apt-get install cmake libopenblas-dev liblapack-dev libarpack2-dev libsuperlu-dev
  - sudo wget http://sourceforge.net/projects/arma/files/armadillo-10.1.2.tar.xz
  - sudo tar -xvf armadillo-10.1.2.tar.xz 
  - cd armadillo-10.1.2 
  - sudo ./configure 
  - sudo make 
  - sudo make install
  - cd ..
script:
  - scons
  - cd unit_tests
  - ./boostTest
  - gcov src/boostTestGrid3D.cpp
  - gcov src/boostTestParabolic.cpp
  - gcov src/boostTestBasisFunction.cpp
  - gcov src/boostTestGeometry.cpp
  - gcov src/boostTestSCFArmaSolver.cpp
after_success:
  - cd ..
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
